"""Generate the Gate A run-matrix configs: 8 cases x {off, raw, smooth}.

Cases = the 5 contested-review words from configs/hard27k/test_sign_hard27k.yaml plus
the 3 worst clips from Gate B's case ranking (outputs/hand_pilot/gate_b/
case_ranking.csv). Everything except the hand_flow fields is held fixed
(graft=true, seed 42, stride 1) so the three arms are strictly paired.

Writes configs/siren/test_sign_handflow_{off,raw,smooth}.yaml.
"""
import argparse
import csv
import os

import _paths as P

BASE_CASES = ["0byrxo0heb", "0ihmqp5iz6", "0hgvcp7paw", "0db3uk2cqw",
              "0hcd4pdr9p"]  # from configs/hard27k/test_sign_hard27k.yaml
VIDEO_DIR = "./assets/example_data/sign_videos/hard27k_orig"
REF_IMAGE = "./assets/example_data/sign_videos/refs/test2.jpg"

HEADER = """\
# Gate A ({arm}): hand_flow channel-causality probe -- {ncases} hard27k cases,
# strictly paired with the other arms (same cases/graft/seed/stride).
# Generated by scripts/hand_pilot/make_arm_configs.py; do not hand-edit.
base_model_path: ./pretrained_weights/stable-video-diffusion-img2vid-xt-1-1
dift_model_path: ./pretrained_weights/stable-diffusion-v1-5

ckpt_path: ./pretrained_weights/MimicMotion_1-1.pth
controlnet_path: ./pretrained_weights/DisPose.pth

test_case:
"""

CASE = """\
  - ref_video_path: {video_dir}/{clip}.mp4
    ref_image_path: {ref_image}
    graft_pose: true
{hand_fields}    num_frames: 16
    resolution: 576
    frames_overlap: 6
    num_inference_steps: 25
    noise_aug_strength: 0
    guidance_scale: 2.0
    sample_stride: 1
    decode_chunk_size: 8
    fps: 30
    seed: {seed}

"""

ARMS = {
    "off": "",
    "raw": "    hand_flow: true\n",
    "smooth": "    hand_flow: true\n    hand_flow_smooth: 1.5\n",
    "siren": ("    hand_flow: true\n"
              "    hand_recon_dir: ./outputs/hand_pilot/hands_recon\n"),
    "gain3": "    hand_flow: true\n    hand_flow_gain: 3.0\n",
    "gain10": "    hand_flow: true\n    hand_flow_gain: 10.0\n",
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ranking",
                    default=os.path.join(P.GATE_B_DIR, "case_ranking.csv"))
    ap.add_argument("--n_extra", type=int, default=3)
    ap.add_argument("--out_dir", default=os.path.join(P.REPO, "configs", "siren"))
    ap.add_argument("--arms", default="",
                    help="comma list; default = all ARMS")
    ap.add_argument("--clips", default="",
                    help="comma list of clip ids overriding case selection")
    ap.add_argument("--all", action="store_true",
                    help="all 109 clips (from the extracted poses dir)")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--suffix", default="",
                    help="override output filename suffix (test_sign_handflow_<suffix>.yaml)")
    ap.add_argument("--shards", type=int, default=1,
                    help="split the case list into N per-shard yamls "
                         "(suffix _full_{k}) to fit slurm time limits")
    args = ap.parse_args()

    cases = list(BASE_CASES)
    if args.all:
        import glob as _g
        cases = sorted(os.path.splitext(os.path.basename(p))[0]
                       for p in _g.glob(os.path.join(P.POSES_DIR, "*.npz")))
    elif args.clips:
        cases = args.clips.split(",")
    elif os.path.exists(args.ranking):
        with open(args.ranking) as f:
            ranked = [r["clip"] for r in csv.DictReader(f)]
        extra = [c for c in ranked if c not in cases][:args.n_extra]
        cases += extra
        print(f"+{len(extra)} worst clips from Gate B: {extra}")
    else:
        print(f"WARNING: {args.ranking} not found -- run gate_b_noise.py "
              f"first; emitting the {len(cases)} base cases only")

    arms = args.arms.split(",") if args.arms else list(ARMS)
    for arm in arms:
        hand_fields = ARMS[arm]
        shards = ([cases] if args.shards <= 1 else
                  [cases[k::args.shards] for k in range(args.shards)])
        for k, shard in enumerate(shards):
            suffix = (f"_{args.suffix}" if args.suffix else
                      (f"_{arm}" if args.shards <= 1 else f"_{arm}_full_{k}"))
            path = os.path.join(args.out_dir,
                                f"test_sign_handflow{suffix}.yaml")
            with open(path, "w") as f:
                f.write(HEADER.format(arm=arm, ncases=len(shard)))
                for clip in shard:
                    f.write(CASE.format(video_dir=VIDEO_DIR,
                                        ref_image=REF_IMAGE, clip=clip,
                                        hand_fields=hand_fields,
                                        seed=args.seed))
            print(f"wrote {path} ({len(shard)} cases)")


if __name__ == "__main__":
    main()
